Repository go-gitea/git, pull requests merged in 2019-02, with the labels that each got.

#142 get branch commit belongs to
  commit.go
  repo_commit.go
Labels: kind/enhancement, lgtm/done

#143 fix get tag list
  repo_tag.go
  repo_tag_test.go
Labels: kind/bug, lgtm/done

#144 add last commit cache interface
  cache.go
  commit_info.go
  commit_info_test.go
Labels: kind/enhancement, lgtm/done

#146 Add myself to maintainers
  MAINTAINERS
Labels: lgtm/done
